example-2/src/blog/urls.py
from django.urls import path
from blog.views import HomePageView, CreatePostView, UpdatePostView, ListPageView, DeletePostView

# enables namespacing
app_name = 'blog'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('posts/', ListPageView.as_view(), name='list-page'),
    path('posts/new/', CreatePostView.as_view(), name='create-page'),
    path('posts/update/<pk>/', UpdatePostView.as_view(), name='update-page'),
    path('posts/delete/<pk>/', DeletePostView.as_view(), name='delete-page')
]

example-2/src/blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()

    def get_update_url(self):
        return reverse('blog:update-page', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('blog:delete-page', args=[str(self.id)])

example-2/src/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=150)
    content = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Post
        fields = '__all__'

example-2/src/blog/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .models import Post
from .forms import PostForm


class HomePageView(generic.TemplateView):
    template_name = 'home.html'


class ListPageView(generic.ListView):
    model = Post


class CreatePostView(generic.CreateView):
    # template used: post_form.html
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:list-page')


class UpdatePostView(generic.UpdateView):
    # template used: post_form.html
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:list-page')


class DeletePostView(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list-page')

example-2/src/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog</title>
</head>
<body>
  <h2>Blog Site</h2>

  <p>
    <span><a href="{% url 'blog:home-page' %}">Home Page</a></span>
    <span> | </span>
    <span><a href="{% url 'blog:list-page' %}">Posts</a></span>
    <span> | </span>
    <span><a href="{% url 'blog:create-page' %}">New Post</a></span>
  </p>
  {% block content %}
  
  {% endblock content %}
</body>
</html>

example-2/src/blog/templates/blog/includes/form.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">{{ label }}</button>
</form>

example-2/src/blog/templates/blog/list.html
{% extends "base.html" %}

{% block content %}
  {% for post in object_list  %}
    <p>{{ post.title }}</p>
    <p>{{ post.content }}</p>
    <p>
      <span><a href="{{ post.get_delete_url }}">Delete</a></span>
      <span> | </span>
      <span><a href="{{ post.get_update_url }}">Edit</a></span>
    </p>
  {% empty %}
    <p>There are no posts to show</p>
  {% endfor %}
{% endblock content %}

example-2/src/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %} 

{% block content  %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.title }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content  %}

example-2/src/blog/templates/blog/post_form.html
{% extends "base.html" %} 

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Post</button>
  </form>
{% endblock content %}

example-2/src/blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
  {% for post in object_list  %}
    <p>{{ post.title }}</p>
    <p>{{ post.content }}</p>
    <p>
      <span><a href="{{ post.get_delete_url }}">Delete</a></span>
      <span> | </span>
      <span><a href="{{ post.get_update_url }}">Edit</a></span>
    </p>
  {% empty %}
    <p>There are no posts to show</p>
  {% endfor %}
{% endblock content %}