example-4/src/blog/urls.py
from django.urls import path
from blog.views import HomePageView, ListPageView, DetailPageView

# enables namespacing
app_name = 'blog'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('posts/', ListPageView.as_view(), name='list-page'),
    path('<slug:slug>/', DetailPageView.as_view(), name='detail-page')
]

example-4/src/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

example-4/src/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

STATUS = (
    (0, 'Draft'),
    (1, 'Publish')
)


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')
    tag = models.ManyToManyField(Tag)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    content = models.TextField()

    def get_update_url(self):
        return reverse('blog:update-page', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('blog:delete-page', args=[str(self.id)])

    def get_details_url(self):
        return reverse('blog:detail-page', args=[str(self.slug)])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    content = models.TextField()
    active = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.content, self.name)

example-4/src/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'content')

example-4/src/blog/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import redirect
from django.urls import reverse
from .models import Post
from .forms import CommentForm
from django.views.generic.detail import SingleObjectMixin
from django.views import View


class HomePageView(generic.TemplateView):
    template_name = 'home.html'


class ListPageView(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    paginate_by = 2


class PostDisplay(generic.DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        post = Post.objects.filter(id=self.object.id)
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


class PostComment(SingleObjectMixin, generic.FormView):
    template_name = 'post_detail.html'
    form_class = CommentForm
    model = Post

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = self.get_form()

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.object
            comment.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('blog:detail-page', args=[str(self.object.slug)])


class DetailPageView(View):
    def get(self, request, *args, **kwargs):
        view = PostDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostComment.as_view()
        return view(request, *args, **kwargs)

example-4/src/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog</title>
</head>
<body>
  <h2>Blog Site</h2>

  <p>
    <span><a href="{% url 'blog:home-page' %}">Home Page</a></span>
    <span> | </span>
    <span><a href="{% url 'blog:list-page' %}">Posts</a></span>
  </p>
  {% block content %}
  
  {% endblock content %}
</body>
</html>

example-4/src/blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
  <p>This is the home page...</p>
{% endblock content %}

example-4/src/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.title }}</h2>
<h5>{{ object.author }} | {{ object.created_on|timesince }} ago</h5>

<p>{{ object.content|safe }}</p>

<hr>
<h3>Comments</h3>
{% for comment in object.comments.all %}
  <p>{{comment.content}}</p>
  <p><b>{{ comment.name }}</b></p>
  <p>---</p>
{% empty %}
  <p>There are no comments to show.</p>
{% endfor %}
<hr>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save Comment</button>
</form>

{% endblock content %}

example-4/src/blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
  {% for post in object_list  %}
    <p>Title: {{ post.title }}</p>
    <p>Content: {{ post.content|truncatewords:9 }}</p>
    <p>
      {% for tag in post.tag.all %}
        <span style="background-color: grey; padding:2px 4px  ; color: #fff;">{{ tag.name }}</span>
      {% endfor %}
    </p>
    <p><span><a href="{{ post.get_details_url }}">Show More</a></span></p>
    <hr>
  {% empty %}
    <p>There are no posts to show</p>
  {% endfor %}


  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <p><a href="?page={{ page_obj.previous_page_number }}">PREV </a></p>
    {% endif %}

    {% if page_obj.has_next %}
      <p><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT</a></p>
    {% endif %}
{% endif %}

{% endblock content %}